### ISSUE TITLE
Bundle Size is Larger than Necessary

### ISSUE THREAD

**Issue by djblue** [connexta/geospatialdraw#1]
The [fontawesome](https://github.com/connexta/geospatialdraw/blob/revelio/package.json#L52-L54) and [lodash](https://github.com/connexta/geospatialdraw/blob/revelio/package.json#L60) dependencies appear to be adding significant overhead to downstream consumers and shouldn't be required for map functionality.

- revelio + openlayer: 2.3M in 30.24s
  ![image](https://user-images.githubusercontent.com/1986211/68270166-b50e0a00-0019-11ea-8837-1e91e13f6161.png)
- revelio + geospatialdraw: bundle.js 3.9M in 44.09s
  ![image](https://user-images.githubusercontent.com/1986211/68270032-3618d180-0019-11ea-9a3e-af42c9d6bcc8.png)

**Comment by BernardIgiri** [comment]
Version v0.5.5 should fix this.
